# Generated by Django 5.1 on 2024-08-18 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_remove_visitante_horario_chegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='horario_chegada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Horário de Chegada na Portaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.PositiveSmallIntegerField(verbose_name='Número da casa a ser visitada'),
        ),
    ]
