# Generated by Django 5.1 on 2024-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail do usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário é da equipe')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Usuário administrador')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
    ]
